name: Laravel CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le code
      uses: actions/checkout@v2

    - name: Installer PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Changez la version si nécessaire
        extensions: mbstring, xml, bcmath, sqlite3, mysql, curl

    # - name: Installer les dépendances
    #   run: |
    #     composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Exécuter les tests
      run: |
        php artisan migrate --env=testing
        php artisan test
