name: Laravel

on:
  push:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    
steps:
 
  - name: Checkout project
    uses: actions/checkout@v3
 
  - name: Initialize PHP ${{ env.php_version }}
    uses: shivammathur/setup-php@v2
    with:
      php-version: ${{ env.php_version }}
      coverage: pcov
 
  - name: Composer install
    run: |
      composer validate --strict
      composer install --optimize-autoloader --no-interaction --prefer-dist
 
  - name: Test
    run: php artisan test
